// crear bronce

CREATE OR REPLACE TABLE B_ORDERS_RAW_COMPLEX (
  ID_ORDER STRING,
  DTE_ORDER STRING,
  ID_CUSTOMER STRING,
  ID_PART STRING,
  QTY_ORDERED STRING,
  AMT_TOTAL STRING,
  REF_PAYMENT_METHOD STRING,
  DTE_DELIVERY_EST STRING,
  DES_ORDER_NOTE STRING
);
